name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-push-backend:
    name: Build and Push Backend Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
# Step to configure AWS environment variables using GitHub secrets
      - name: Configure AWS environment variables
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "GOOGLE_OAUTH2_CLIENT_ID=${{ secrets.GOOGLE_OAUTH2_CLIENT_ID }}" >> $GITHUB_ENV
          echo "GOOGLE_OAUTH2_CLIENT_SECRET=${{ secrets.GOOGLE_OAUTH2_CLIENT_SECRET }}" >> $GITHUB_ENV

      - name: Build Backend
        run: |
          cd fileapp
          ./gradlew build --no-daemon

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image for Backend
        run: |
          cd fileapp
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fileapp-backend:latest .

      - name: Push Docker Image for Backend
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fileapp-backend:latest

  build-and-push-frontend:
    name: Build and Push Frontend Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: fileapp-ui/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('fileapp-ui/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: |
          cd fileapp-ui
          npm install

      - name: Build Frontend
        run: |
          cd fileapp-ui
          npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image for Frontend
        run: |
          cd fileapp-ui
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fileapp-frontend:latest .

      - name: Push Docker Image for Frontend
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fileapp-frontend:latest
